config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "foods#index"
  resources :foods do
    resource :likes, only: [ :create, :destroy ]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_one_attached :avatar
  validates :name, presence: true
  validates :avatar, content_type: [ "image/png", "image/jpeg", "image/gif" ]
  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :food

  validates :user_id, uniqueness: {
    scope: :food_id,
    message: :duplicated
  }

  validate :forbid_to_owner

  private

  def forbid_to_owner
    return unless user && food
    errors.add(:base, :owner_forbidden) if user_id == food.user_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_foods, through: :likes, source: :food
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[edit update destroy]
  def index
    @foods = Food.includes(:user, :likes).order(created_at: :asc)
  end

  def new
    @food = Food.new
  end

  def create
    food = current_user.foods.create!(food_params)
    # food = Food.new(food_params)
    # food.user_id = current_user.id
    # food.save!
    redirect_to food
  end

  def show
    @food = Food.find(params[:id])
  end

  def edit
  end

  def update
    @food.update!(food_params)
    redirect_to @food
  end

  def destroy
    @food.destroy!
    redirect_to root_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :comment, :avatar)
  end

  def set_food
    # 「自分の投稿」の中から URL の :id に対応する投稿を探す
    # 「他人の投稿」の場合はエラーを出す.find メソッドを使用すると，他人の投稿の場合にエラーが発生します。
    @food = current_user.foods.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_food

  def create
    current_user.likes.create!(food_id: @food.id)
  end

  def destroy
    current_user.likes.find_by(food_id: @food.id).destroy
  end

  private

  def set_food
    @food = Food.find(params[:food_id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  devise_for :users, controllers: {
  sessions: "users/sessions"
}
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/_food.html.erb
<div>
  <p>【メールアドレス】 <%= food.user.email %></p>
  <p>【食品名】 <%= food.name %></p>
  <%= render "like", food: food, is_liked: food.likes.any? { |like| like.user_id == current_user.id } %>
  <p>
    <%= link_to "詳細", food %>
    <% if current_user.id == food.user_id %>
      <%= link_to "編集", edit_food_path(food) %>
      <%= link_to "削除", food_path(food), data: { turbo_method: :delete, turbo_confirm: "削除してよろしいですか？" } %>
    <% end %>
  </p>
</div>
<hr>

app/views/foods/_form.html.erb
<%= form_with model: @food do |form| %>
  <div>
    <label for="name">料理名</label>
    <%= form.text_field :name, required: true %>
  </div>
  <div>
    <%= form.file_field :avatar, accept: "image/png,image/jpeg,image/gif" %>
  <div>
    <label for="name">コメント</label>
    <%= form.text_area :comment %>
  </div>
  <%= form.submit "送信" %>
<% end %>

app/views/foods/_like.html.erb
<% unless defined?(is_liked) %>
  <% is_liked = food.liked_by?(current_user) %>
<% end %>

<p id="<%= dom_id(food, :like) %>">
  <% if is_liked %>
    <%# 「いいね！」済み %>
    <%= link_to "★", food_likes_path(food), data: { turbo_method: :delete } %>
  <% else %>
    <%# 「いいね」していない %>
    <%= link_to "☆", food_likes_path(food), data: { turbo_method: :post } %>
  <% end %>
</p>

app/views/foods/edit.html.erb
<h1>編集</h1>
<%= render "form" %>

app/views/foods/index.html.erb
<h1>投稿一覧</h1>
<%= render @foods %>

app/views/foods/new.html.erb
<h1>新規投稿</h1>
<%= render "form" %>

app/views/foods/show.html.erb
<h1>投稿詳細</h1>
<p>【メールアドレス】 <%= @food.user.email %></p>
<p>【料理名】 <%= @food.name %></p>
<%= render "like", food: @food %>
<% if @food.avatar.attached? %>
  <div>
    <%= image_tag @food.avatar %>
  </div>
<% end %>
<p>【コメント】 <%= simple_format(h(@food.comment)) %></p>
<% if current_user.id == @food.user_id %>
  <p>
    <%= link_to "編集", edit_food_path(@food) %>
    <%= link_to "削除", food_path(@food), data: { turbo_method: :delete, turbo_confirm: "削除してよろしいですか？" } %>
  </p>
<% end %>
<p><%= link_to "投稿一覧へ", foods_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Recommended Food App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "アカウント編集", "/users/edit" %>
      <%= link_to 'ログアウト', "/users/sign_out", data: { turbo_method: :delete } %>
      <%= link_to "一覧ページ", "/" %>
      <%= link_to "新規投稿ページ", "/foods/new" %>
      <%= current_user.email %>
    <% else %>
      <%= link_to "ログイン", "/users/sign_in" %> 
      <%= link_to "アカウント登録", "/users/sign_up" %> 
    <% end %> 
    <%= yield %> 
  </body>
</html>

app/views/likes/create.turbo_stream.erb
<%= turbo_stream.replace dom_id(@food, :like) do %>
  <%= render "foods/like", food: @food, is_liked: true %>
<% end %>

app/views/likes/destroy.turbo_stream.erb
<%= turbo_stream.replace dom_id(@food, :like) do %>
  <%= render "foods/like", food: @food, is_liked: false %>
<% end %>